### ISSUE TITLE
Metamorph Teleport Ability spamming NoSuchMethod on Server

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#11]
Pack Version 1.11

Whenever a player Teleports on the server using Enderman morph a NoSuchErrorMethod is thrown on the server.
``` java
[02:27:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
    at mchorse.vanilla_pack.actions.Teleport.execute(Teleport.java:34) ~[Teleport.class:?]
    at mchorse.metamorph.api.morphs.AbstractMorph.action(AbstractMorph.java:236) ~[AbstractMorph.class:?]
    at mchorse.metamorph.network.server.ServerHandlerAction.run(ServerHandlerAction.java:22) ~[ServerHandlerAction.class:?]
    at mchorse.metamorph.network.server.ServerHandlerAction.run(ServerHandlerAction.java:11) ~[ServerHandlerAction.class:?]
    at mchorse.metamorph.network.server.ServerMessageHandler$1.run(ServerMessageHandler.java:26) ~[ServerMessageHandler$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
    ... 5 more
```

Metamorph appears to be invoking Entity getPositionEyes on the Server. This is a Client Only function.

**Comment by mallrat208** [comment]
Closing this as this issue should be fixed as of the last update of Metamorph we included in the pack
